### ISSUE TITLE
Управление высоковольтными устройствами

### ISSUE THREAD

**Issue by yurboc** [yurboc/Yurix#1]
Надо изменить логику работы летниц Якова.
Включение - как и раньше, при выполнении соответствующего условия.
Выключение - только при откытии дверей в "машину времени" (когда выполнены все условия).

**Comment by Falc-0n** [comment]
Ура! Комменты работают.
Юр подскажи, где найти последние версии твоих исходников?

**Comment by yurboc** [comment]
Ура! Я тебе сегодня вечером отправлю патчи,
ты сможешь их применить на текущую версию своего кода.
Можешь смело комитить то, что уже сделал! Это не помешает

**Comment by Falc-0n** [comment]
Юр, пришли пожалуйста новые исходники. К утру я обещал Саше готовую прошивку.

**Comment by yurboc** [comment]
Всё что было я отправил Саше.
Ты сейчас на квесте? Можешь сразу проверить на железе и закоммитить, если всё работает.
Мы с ним этот код не до конца проверили.

**Comment by Falc-0n** [comment]
Я дома. Мы с ним договорились, что объединю вчерашние правки с твоим последним кодом, вышлю прошивку .hex, а он зальет.
Не сможешь сюда закинуть последние версии?

**Comment by yurboc** [comment]
Лучше отправь сейчас на сервер все свои изменения, которые ты уже проверил на железках, а потом применишь мои изменния. Так лучше, чем объединять всё в одно.

**Comment by Falc-0n** [comment]
Ок, написал Саше. Как пришлет файлы, доделаю. Спасибо)

**Comment by yurboc** [comment]
Перенесены изменения из 4da3e535905870b068e11443462c427edd9363fa
