### ISSUE TITLE
Настроить Горгону

### ISSUE THREAD

**Issue by yurboc** [yurboc/Yurix#10]
Нужно снизить порог срабатывания горгоны, сейчас она срабатывает от тени, которую отбрасывает человек.

**Comment by yurboc** [comment]
Исправлять здесь:
https://github.com/yurboc/Yurix/blob/master/FreeRTOS/Projects/TeslaMainBoard/tasks-common/cabinet.c#L8

Значения - от 4095 (надо накрывать очень плотной тканью для срабатывания) до 2000 (срабатывает от малейшей тени).

**Comment by Falc-0n** [comment]
Сейчас стоит 3820. Это, выходит, почти минимум чувствительности на тень - сильно не разбежишься.. но будем тестить. Там несколько фотодатчиков вверху головы расположено?

**Comment by yurboc** [comment]
Там 4 фототранзистора. Срабатывание идёт по наиболее освещённому, т.е. если ты закрыл 3, а на 1 свет всё ещё попадает, то "условие не выполнено".

Посмотри, как было до исправления:
https://github.com/yurboc/Yurix/commit/d97874cfac541d25dfa447255cb4ed64cfa8f4ae#diff-8b9ac90403f81a2f279d60cfb5923437L8

ANALOG_IN_ADC_ADC_MAX_VALUE - 1
(это соответствует значению 4095-1, при котором горгона срабатывала, если её накрыть двумя тряпками и коробкой)
Попробуй снова поставить это значение. Или чуть меньше, например
ANALOG_IN_ADC_ADC_MAX_VALUE - 5

**Comment by Falc-0n** [comment]
Корректировка кода только частично спасает, увы. Придется мешок сделать более плотным, иначе она тень человека и надетый мешок плохо отличает. Хотя, уже лучше.

**Comment by yurboc** [comment]
В таком случае экспериментируй в пределах от
**ANALOG_IN_ADC_ADC_MAX_VALUE - 5**
до
**ANALOG_IN_ADC_ADC_MAX_VALUE - 1**

При этом для "ANALOG_IN_ADC_ADC_MAX_VALUE - 1" мешок нужен очень плотный, нам приходилось даже коробку одевать. Для значений "ANALOG_IN_ADC_ADC_MAX_VALUE - 3" и меньше, скорее всего, можно уже будет без коробки. Начиная где-то с "ANALOG_IN_ADC_ADC_MAX_VALUE - 5" может реагировать на тень при таком слабом освещении, как сейчас.

**Comment by Falc-0n** [comment]
Я протестил много разных значений, выше примерно 3850 на загораживание ближней лампы уже не реагирует (я вообще эту лампочку выкрутил). Но 3850 не дает срабатывание и с нашим прозрачным мешком :)) это не проблема, мешок сделают плотнее, я подниму значение и должно быть ОК.

**Comment by yurboc** [comment]
по описанию больше похоже на то, что один из фототранзисторов сдох)) как в IAR ставить точку останова знаешь? посмотри, какие значения приходят с датчиков вот в этот момент:
https://github.com/Falc-0n/Yurix/blob/master/FreeRTOS/Projects/TeslaMainBoard/tasks-common/cabinet.c#L79

**Comment by AlexMarkin** [comment]
Сейчас мешка не хватает, т.е. приходится просить людей загородить горгону еще и телом.

**Comment by yurboc** [comment]
Ок, сделайте следующее. В строке
https://github.com/Falc-0n/Yurix/blob/master/FreeRTOS/Projects/TeslaMainBoard/tasks-common/cabinet.c#L79
напишите
`xprintf("> Value on 1 transistor is %d\n", STM_TESLA_ANALOGGetValue(ANALOG_IN_HEAD1);`
`xprintf("> Value on 2 transistor is %d\n", STM_TESLA_ANALOGGetValue(ANALOG_IN_HEAD2);`
`xprintf("> Value on 3 transistor is %d\n", STM_TESLA_ANALOGGetValue(ANALOG_IN_HEAD3);`
`xprintf("> Value on 4 transistor is %d\n\n", STM_TESLA_ANALOGGetValue(ANALOG_IN_HEAD4);`
после этого закройте управляющую программу и откройте терминалом (например PuTTY) тот порт, на котором висит центральная плата управления. Значения увидите на терминале в реальном времени. Накрыв горгону тряпкой, значения станут ближе к 4095, сняв тряпку, значения станут меньше. Запишите все 4 значения при накрытой горгоне и используйте их.

**Comment by yurboc** [comment]
Номер порта (например, COM5) отображается в программе оператора. Остальные настройки в PuTYY по-умолчанию выставлены правильные (9600-8N1).

Данные начнут приходить только тогда, когда Горгона включится.
Если ничего не происходизойдёт, попробуйте опросить плату командой `>?`
Остальные команды здесь: https://github.com/Falc-0n/Yurix/blob/master/FreeRTOS/Projects/TeslaMainBoard/tasks-common/communication.c#L18

Если и это не сработает, смотрите на плату управления:
https://raw.githubusercontent.com/Falc-0n/Yurix/master/Documentation/Hardware/TeslaMainBoard/TeslaMainBoard_layout.jpg
чуть выше и левее разъёма 51 два светодиода - зелёный и красный. Мигают при передаче данных на плату управления и получения состояния с ней.

**Comment by Falc-0n** [comment]
Завтра это проделаю.
Странно что сейчас не хватает мешка, я тестил утром и так и эдак. Может это тот самый дрейa напряжения, о котором мы говорили. А может правда с датчиками что-то.

**Comment by yurboc** [comment]
Я подозреваю датчики, потому что раньше всё работало идеально. Если хоть один датчик оборван, с него будет приходить что-то близкое к 4095 (либо около 0, если его коротнуло на землю).

**Comment by Falc-0n** [comment]
Проверили значения на датчиках через программу, они примерно одинаковые все. 
Нужен более плотный мешок на Горгону, и под него если нужно - небольшая корректировка порогового значения.
