### ISSUE TITLE
Проверка даты в машине времени

### ISSUE THREAD

**Issue by yurboc** [yurboc/Yurix#11]
В машине времени правильная дата должна сработать только если рычаг постоял на правильном значении 3-5 секунд (сейчас это можно сделать наобум). Из-за особенностей этого устройства там не приходит постоянный сигнал в течение даже 3 секунд, но можно симитировать эту логику. Например, правильный сигнал должен придти 20 раз за эти 3 секунды.

**Comment by Falc-0n** [comment]
Правлю файл timemachine.c, так? Раз в какое время (~примерно) от машины приходит сигнал "верная дата", если дата все время выставлена правильно?

**Comment by yurboc** [comment]
Да, так.
Примерно раз в три секунды: выставили сигнал - ждём секунду - сняли сигнал. Затем 3 секунды - звук из пищалки, затем повторная проверка условий в цикле, затем снова попадаем в это условие и снова выставляем сигнал.

**Comment by Falc-0n** [comment]
Если правильно тебя понял, надо сделать в обработчике сигнала от машины следующее:
чтобы запуск перемещения во времени начинался после подряд двух сигналов от машины, причем второй должен прийти в течении 3-4 сек после первого, иначе сброс.
А пищалка где стоит, прямо в машине на плате с AVR, или на ЦП в шкафу где STM?

**Comment by yurboc** [comment]
Так, я тебя похоже запутал) От машины времени сигнал "верная дата" не приходит. От неё вообще никакого сигнала не приходит: там переменные резисторы и индикаторы.

Центральный контроллер (на ЦП в шкафу) определяет, на какой угол повёрнуты ручки (измеряет их сопротивление) и на индикаторы отправляет цифры.

Центральный контроллер сам решает, выставлена ли правильная дата или нет.

Центральный контроллер проверяет это здесь:
https://github.com/Falc-0n/Yurix/blob/master/FreeRTOS/Projects/TeslaMainBoard/tasks-common/timemachine.c#L127
а использует - здесь: (условие "если дата правильная и нажаты кнопки")
https://github.com/Falc-0n/Yurix/blob/master/FreeRTOS/Projects/TeslaMainBoard/tasks-common/timemachine.c#L131
Кстати, рекомендую переименовать INPUT_5 в INPUT_LAB_TM_GREEN_BUTTONS

**Comment by Falc-0n** [comment]
А, так это кажется легко реализовать! 
Если сделаем что-то вроде 
if (checkCorrectDate(monthValue, dayValue) == 1) correct_date_wait++; //инкремент если верно
if (checkCorrectDate(monthValue, dayValue)  != 1) correct_date_wait=0; //сброс если сбили дату

и по достижению correct_date_wait какого-то значения (сколько циклов продержалась верная дата) делаем 
rightDateSet = 1;

**Comment by yurboc** [comment]
Всё правильно. На каждом цикле будет проходить около mainMIN_CHECKING_DELAY_MS миллисекунд. Зная, сколько времени надо ждать, подбираешь количество циклов ожидания.

**Comment by AlexMarkin** [comment]
Насколько я вижу, эта вещь заработала корректно.
