### ISSUE TITLE
Добавить задержку включения

### ISSUE THREAD

**Issue by yurboc** [yurboc/Yurix#12]
Нужно, чтобы Лестницы Иакова и Генератор Маркса включались после только трех секунд получения правильного сигнала.

**Comment by Falc-0n** [comment]
В каком файле описано ожидание сигналов от крутилок и тумблеров?

**Comment by yurboc** [comment]
Пока что ни в каком. Раньше такого не требовалось.

**Comment by Falc-0n** [comment]
Я не так написал, в смысле в каком файле обрабатываются сигналы "верно" от тумблеров и крутилок? В hightvoltage.c?

**Comment by yurboc** [comment]
Здесь
https://github.com/Falc-0n/Yurix/blob/master/FreeRTOS/Projects/TeslaMainBoard/tasks-common/hightvoltage.c#L33
здесь
https://github.com/Falc-0n/Yurix/blob/master/FreeRTOS/Projects/TeslaMainBoard/tasks-common/hightvoltage.c#L45
и здесь
https://github.com/Falc-0n/Yurix/blob/master/FreeRTOS/Projects/TeslaMainBoard/tasks-common/hightvoltage.c#L57

(комментарии см. перед каждой из этих строк, там написано что для чего)

**Comment by yurboc** [comment]
После тех изменений в 0e303cb9694f685bf21755a47fd551e1fa039e2c всё стало работать? Если да, то можешь закрыть задачу.

**Comment by Falc-0n** [comment]
Да, все работает нормально.
