### ISSUE TITLE
Диммер не работает

### ISSUE THREAD

**Issue by Falc-0n** [yurboc/Yurix#15]
Юр, после поворота ключей в шкафу = открытия лаборатории, свет в кабинете просто гаснет, а не включаются диммеры.На сегкунду везде полная темнота, потом загорается свет в лаборатории. Из-за чего такое может быть?
У меня в репозитории все коммиты актуальны, я сейчас на квесте.

upd Иногда работают, чаще нет. Причина пока непонятна.

**Comment by yurboc** [comment]
Открой крышку в верхней правой распаячной коробке (с надписью "свет") и поверни ручку диммера, чтобы немного увеличить яркость подсветки.

**Comment by Falc-0n** [comment]
Он не то чтобы слишком тусклый, он просто в 95% случаев не включается при открывании лаборатории. Или это в железе проблема, в самом диммере?

**Comment by yurboc** [comment]
это проблема в том, что триак не открывается на очень малых напряжениях. увеличив яркость (даже совсем немного), он будет, скорее всего, работать гораздо стабильнее

**Comment by Falc-0n** [comment]
А я думал, что прошивка подглючивает. Завтра-послезавтра попробую.

**Comment by yurboc** [comment]
попробуй поуправлять диммером из программы оператора. там есть кнопка для этого

**Comment by yurboc** [comment]
Попробовал? Диммер стал работать нормально?

**Comment by Falc-0n** [comment]
Вчера до часа с крутилками занимался, на остальное меня не хватило.

**Comment by Falc-0n** [comment]
Попробовал увеличить яркость, все также: иногда работает, немного притухает, а чаще гаснет совсем. Может это зависит от фазы сети в момент включения?

**Comment by yurboc** [comment]
Больше похоже на выход из строя переменного резистора в диммере. Попробуй настроить на оптимальную яркость, отпаяй непременный и припаяй такой же, но постоянный. Там около 5кОм надо, если я не ошибаюсь.

**Comment by Falc-0n** [comment]
Как устроено переключение между двумя режимами (с диммером и без)?
В режиме "кабинет" диммер просто закорачивается замкнутым реле? И когда открываем лабораторию, реле размыкается, добавляя в цепь диммер?

**Comment by yurboc** [comment]
Именно так. Единственное, что это не одно и тоже реле, а два независимых.

**Comment by Falc-0n** [comment]
Не соображу, как подключено второе реле? Первое замыкает диммер, когда нужен полный свет. Размыкается, когда открываем кабинет. А второе?

**Comment by yurboc** [comment]
А второго нет. Ты о каком?
Управляет светом всего два реле: первое лабораторией, второе кабинетом.

**Comment by Falc-0n** [comment]
Все, теперь понял. То есть 100% глюк в диммере. Я для начала его подвигаю как буду на квесте, может банальный неконтакт.

**Comment by AlexMarkin** [comment]
Ребята, я так понимаю, что вариант с неконтактом не сработал. Надо менять диммер тогда? Какой купим? Денис, сделай эту штуку, пожалуйста.

**Comment by Falc-0n** [comment]
Сегодня если буду, подергаем диммер. Его ведь можно принудительно включить с компа?
Прокину другой резистор, если понадобится. Там ломаться почти нечему.) Ну а если ничего не поможет, купим любой магазинный на суммарную мощность люстр, плюс небольшой запас.

**Comment by AlexMarkin** [comment]
Денис перепаял, жалобы от операторов больше не поступают.
