### ISSUE TITLE
Автоматический перевод даты

### ISSUE THREAD

**Issue by AlexMarkin** [yurboc/Yurix#16]
Сейчас не переводится правильная дата в машине времени, это надо делать в ручную.
Можно ли поправить этот момент?

**Comment by yurboc** [comment]
В логах (на второй странице программы оператора) дата правильная отображается? Она там насчитывается с внутренних часов центрального контроллера.

**Comment by Falc-0n** [comment]
Саш, проверь пожалуйста дату в логах программы. Если неправильная, перешьем как Юра написал.

**Comment by AlexMarkin** [comment]
Как это проверить? 
Нажать "пров машину времени"?
Если так, то она показывает ведь время, которое на часах отображается?

**Comment by Falc-0n** [comment]
Сложно понять, не видя программу (у меня без платы не переключается на вторую вкладку). 
Но судя по алгоритму прошивки контроллера, после срабатывания машины времени (когда все условия будут выполнены) в поле логов (внизу на второй вкладке) будет написано "TM Done, ...". 
Вот эта строка интересна. Должно выйти время в порядке, как здесь: 
currentDay, currentMonth, currentYear, currentHour, currentMin, currentSec
Если сегодня дату не обновлял, попробуй так сделать - какую дату покажет в этой строке?

**Comment by AlexMarkin** [comment]
Понял, завтра сделаю

**Comment by Falc-0n** [comment]
Батарейку часов поменял, пока все тикает правильно. Будем наблюдать.

**Comment by yurboc** [comment]
Если замена батарейки не поможет, и часы будут останавливаться даже при наличии питания, то нужно будет немного доработать функцию опроса времени: каждый раз, считывая значение из RTC, надо проверять, не установлен ли флаг Clock Halt. И если окажется, что установлен, то сразу его сбрасывать.

**Comment by yurboc** [comment]
Кроме разрядившейся батарейки есть ещё одна возможная причина сбоя - всё те же высоковольные установки и помехи по линиям питания. Микросхема часов чувствительна к ним.

**Comment by Falc-0n** [comment]
По какой причине может сам устанавливаться флаг HALT? Ведь даже если будем его сбрасывать каждый раз, потеряем как минимум несколько тактов?

**Comment by yurboc** [comment]
Это просто предположение. Флаг HALT устанавливается, если с осциллятором произошло что-то непредвиденное, или если пропадало питание (посмотри по даташиту). По идее, без всякой видимой причины он не должен устанавливаться вообще.

**Comment by AlexMarkin** [comment]
Ребята по прежнему не работает, надо что-то делать. Давайте попробуем Юрины идеи реализовать.

**Comment by Falc-0n** [comment]
Интересно следующее. Часы тикают нормально, пока включено питание платы. А потом вообще перестают идти, даже когда возвращаем питание. В какой момент перестают - пока не понятно. 
Но может, дело в простом неконтакте в цепи батарейки? Ок, я попробую принудительно сбрасывать HALT.

**Comment by yurboc** [comment]
В цепи батарейки все провода пропаяны, там вряд ли может быть проблема.
Во время работы платы каждую секунду идёт опрос часов. Ты можешь добавить функцию, которая будет считывать флаг HALT, и если он установлен - сбрасывать его (возможно, сообщив оператору).

**Comment by yurboc** [comment]
Попросите операторов в начале дня нажимать кнопку "Получить время". И только в том случае, если часы показывают неправильную дату и время, нажимать "Установить время".

Я за последние дни проблем со схемой часов не наблюдал, время всегда было правильное.
