### ISSUE TITLE
Не срабатывают кнопки в машине времени

### ISSUE THREAD

**Issue by AlexMarkin** [yurboc/Yurix#17]
Нажатие кнопок не давало сигнал о том, что контакт есть. Есть гипотеза, что одна из кнопок вышла из строя.

**Comment by AlexMarkin** [comment]
Одну кнопку напрямую запитал на плату, т.е. теперь для запуска можно нажать эту кнопку либо одновременно три другие. Вроде работает.

**Comment by Falc-0n** [comment]
Хочешь сказать, обрыв в соединениях между кнопками, а сами кнопки все работают?

**Comment by AlexMarkin** [comment]
Нет, думаю, что проблема в одной или нескольких кнопках.
Бутафоры сделали разводку очень криво, поэтому там невозможно понять, какие именно провода за что отвечают. Это мешает оперативно прозвонить каждую кнопку.  
 Все кнопки вместе дают контакт очень нестабильно. 
Сейчас я взял крайнюю кнопку, нашел в ней контактные провода и подключил ее параллельно трем другим кнопкам. Судя по тому, что стало работать, проблема в одной из трех оставшихся кнопок.

**Comment by Falc-0n** [comment]
Они выковыриваются из стенки? Может так легче проверить?

**Comment by AlexMarkin** [comment]
Они сложно выковыриваются. Насколько я могу судить, они закручены с обратной стороны, т.е. надо длинной рукой открутить крепеж . 
Давай пока отложим эту задачу, вроде работает нормально, если не будет вызывать проблем, то пусть так и будет.
