### ISSUE TITLE
Плата работает нестабильно

### ISSUE THREAD

**Issue by AlexMarkin** [yurboc/Yurix#18]
Я замечаю некоторую нестабильность работы центрального устройства. 
Иногда случаются моменты, что плата перестает корректно работать: не открывает проектор, не включает лестницы, не открывает машину времени (один из списка или все вместе). В такие же моменты плата перестает реагировать на программу, например, при нажатии "опр. лабораторные устройства" ничего не появляется. Помогает только полная перезагрузка, т.е. отключение от питания и от USB. 
Что происходит?
Если плата зависает, то как можно от этого избавиться?

**Comment by Falc-0n** [comment]
Юр, у STM есть что-то вроде watchdog'а?

**Comment by AlexMarkin** [comment]
Можно как то понять, зависла плата или нет? И что вообще с ней?

**Comment by yurboc** [comment]
Да, в микроклнтроллере есть сторожевой таймер. Но если вы его задействуете, квест будет сбрасываться в исходное состояние при каждом зависании.

Да, обнаружить зависание платы можно. В нормальном режиме на плате раз в секунду вспыхивает зелёный светодиод.

Чтобы найти проблему, запустите прошивку в отладочном режиме из-под IAR. Как только зависнет - останввливайте и смотрите, на каком участке кода произошёл сбой.

**Comment by yurboc** [comment]
Предположительно, причиной зависаний была некорректная работа с микросхемой RTC.

Плата зависла, если не мигает зелёный светодиод (см. компонент "49" на рисунке https://raw.githubusercontent.com/yurboc/Yurix/master/Documentation/Hardware/TeslaMainBoard/TeslaMainBoard_layout.jpg)

Если зависания повторятся, переоткрывайте эту задачу.
