### ISSUE TITLE
Убрать условия прождения квеста

### ISSUE THREAD

**Issue by AlexMarkin** [yurboc/Yurix#19]
Ребята,
я подумал и понял, что условие для работы оборудования лаборатории и внутренностей машины времени избыточны.

Т.е. я бы хотел убрать из кода кусок, из-за которого Иаков, графит и прочее не включается, если кабинет не открыт, а также условие, что цифры в машине времени становятся активны, только после открытия машины времени. Пусть и то, и другое всегда будет активно. 
Это будет доп. гарантией, что операторы не забудут выключить тумблеры и упростит управление квестом с компьютера.

**Comment by yurboc** [comment]
Просто установите биты прохождения на этапе инициализации (а не в момент выполнения условия, как это сделано сейчас). Эта группа битов называется как-то типа opened_locks

**Comment by yurboc** [comment]
В управляющую программу добавлены кнопки перехода на любой этап квеста.
