### ISSUE TITLE
Шестая лампа в м.в. не показывает ноль

### ISSUE THREAD

**Issue by AlexMarkin** [yurboc/Yurix#20]
Шестая лампа на панели машины времени перестала показывать ноль. Остальные цифры вроде показывает хорошо. Что могло произойти?

**Comment by yurboc** [comment]
Однозначно отвалился провод катода. Причём наверняка со стороны лампы. Снимайте крышку сзади и смотрите.

Если бы выгорели микросхемы - погас бы ноль на всех лампах, если анодные транзисторы - на 6-й лампе погасли бы все цифры.

**Comment by AlexMarkin** [comment]
Это хорошие новости)

**Comment by Falc-0n** [comment]
fixed

**Comment by Falc-0n** [comment]
Юра, привет! Увы, один раз ноль стал работать сам, а после снова пропал. И вот до сих пор не могу найти причину. Проверил контакты сзади за лампами, спереди на платах под ручками даты. Кажется, что все на месте.

Есть одна особенность, когда должен гореть "0", в лампе светится небольшой кусочек сверху, и больше ничего. Такое ощущение, что питающее напряжение пороговое для лампы, и она то зажигает цифру, то нет. И ноль же самый далекий от анода? Такое может быть? 
Или сама лампа могла испортиться?

**Comment by yurboc** [comment]
Привет, Денис. Смотри, там стоят лампы ИН-4, вот они: http://www.radiolamp.ru/sprav/ind/in4.html
Как видишь, напряжение зажигания 170 вольт. Измерь напряжение между анодом и катодом цифры "0" напряжение в режиме постоянного горения. Если не хватает - на блоке повышения напряжения увеличь его подстроечным резистором (ты увидишь отверстие в корпусе).

**Comment by yurboc** [comment]
А ещё лучше - убедись, что на выходе блока повышения 170В или больше. На лампах измерять особого смысла нет, там импульсное напряжение. Только если сравнить с другими лампами...

**Comment by Falc-0n** [comment]
ОК, попробую, спасибо. 
На всякий случай, где они покупались? Вот фото того что есть, и пример когда ноль горит. Видно, что горит слабее других почему-то.
![20150516_001603](https://cloud.githubusercontent.com/assets/11696225/8177580/c04d5570-140e-11e5-98a5-7a3698375eb3.jpg)
![20150516_001621](https://cloud.githubusercontent.com/assets/11696225/8177581/c04dcf64-140e-11e5-923f-144644092169.jpg)
![20150517_232143](https://cloud.githubusercontent.com/assets/11696225/8177582/c04eaefc-140e-11e5-9d5f-dd6b5f008158.jpg)
![20150517_232643](https://cloud.githubusercontent.com/assets/11696225/8177583/c04f5eb0-140e-11e5-8e7a-52c5f79615dc.jpg)

**Comment by yurboc** [comment]
Покупались в Кварце на шоссе Энтузиастов.

**Comment by yurboc** [comment]
Все остальные цифры на этой лампе хорошо горят? Очень смахивает на замыкание катодов.
Попробуй всё-таки прозвонить все катоды между собой. 
У меня ещё есть такие лампы. Если совсем не получится, я к вам на неделе заеду, посмотрю.
Вообще такие лампы из строя выходить не должны. Внутри там только пластины и газ.

**Comment by yurboc** [comment]
Я посмотрел эту лампу. Она неисправна физически, её необходимо заменить.
Когда я подключал другие лампы вместо этой, они работали.
