### ISSUE TITLE
Новая динамка

### ISSUE THREAD

**Issue by AlexMarkin** [yurboc/Yurix#21]
Коллеги, 
В новой динамо-машине будет один энкодер и два устройства, которым он нужен: устройство производящее искры и устройство увеличивающее "заряд" батареи. Договоритесь между собой, пожалуйста, как вы организуете взаимодействие устройств до того, как Денис соберет финальную версию.

**Comment by yurboc** [comment]
Устройству, увиличивающему заряд батареи, нужно всего лишь количество сделанных оборотов. Готов принимать на своё устройство импульсный сигнал (toggle) напряжением 5В наждые 1/4 оборота.

**Comment by Falc-0n** [comment]
Тут два варианта, или 1) оставить как было - сигнал с энкодера снимается сразу двумя устройствами, или 2) как ты предложил, мой блок снимает сигнал и передает на центральную плату одним проводом каждые 1/4 оборота. 
Мне пока второй больше нравится, попробую его реализовать, дайте день-два.

Какая минимальная продолжительность импульса нужна каждые 1/4 оборота, чтобы ЦП надежно распознавала сигнал?

**Comment by Falc-0n** [comment]
И еще. Допустим ли другой период сигнала (например каждые 1/3 или 1/5 оборота) - в программе ЦП ведь можно скорректировать шаг ШИМа для управления стрелочником?
У меня будет отрабатываться искрение при вращении ручки, было бы здорово привязать отправку сигнала на ЦП к срабатыванию искры.

**Comment by yurboc** [comment]
Минимальная длина импульса будет зависеть от скорости вращения ручки: ты просто меняй состояние выхода на противоположное (toggle).

Другой период допустим, можешь и 1/24 оборота сделать. Главное не реже 1/2 оборота, потому что стрелка должна подниматься плавно, без рывков.

**Comment by Falc-0n** [comment]
Ок, сделал каждые 1/24. 
Прибор готов)
STM не обидится на амплитуду сигнала 5В?

**Comment by yurboc** [comment]
Да любой пойдёт, я через оптопару буду подключать.

**Comment by yurboc** [comment]
Новую динамку проверил (ещё тогда, когда она лежала в мастерской).
Моё устройство управления работает с ней стабильно.
