### ISSUE TITLE
Повышаем глюкоустойчивость крутилок

### ISSUE THREAD

**Issue by Falc-0n** [yurboc/Yurix#3]
Нужно понизить рабочую частоту платы. От чего по умолчанию тактируется STM32f0 на этой плате? В настройках стоит HSE, а с чего снимается тактовый сигнал?

**Comment by yurboc** [comment]
В настройках чего? Посмотри в файле
https://github.com/yurboc/Yurix/blob/master/Projects/EncodersToArrows/system_stm32f0xx.c#L103
Ты ведь его используешь?

**Comment by Falc-0n** [comment]
ОК, значит напутал я что-то. Получается, в текущей версии тактирование (HSI/2) -> PLL (х12) ?
Если я снижу частоту, например до 1 или 8 МГц, какие параметры в коде нужно скорректировать, чтобы стрелки нормально отрабатывали?

**Comment by yurboc** [comment]
Я ставил все настройки по-умолчанию, поэтому точно не могу сейчас сказать частоты шин.
Если снизишь частоту, ещё не факт, что девайсы не будут реагировать на помехи от высоковольтных устройств. Многие сигналы обрабатываются асинхронно и не зависят от частоты.
Попробуй скомпиллировать с пониженной частотой и залить прошивку на контроллер. Если будет работать (хоть как-то), ты сам поймёшь, какие параметры надо менять (настройки таймеров). Но я думаю, что это не спасёт от помех. Надо ставить рассчитывать и ставить RC-фильтры на входах...

**Comment by Falc-0n** [comment]
Я уже пробовал снижать, стрелки замедляются пропорционально. В каком файле находятся настройки таймеров? Я вчера только прошил на меньшую частоту и обратно, уже был час ночи, не стал разбираться в чем дело.)

**Comment by yurboc** [comment]
Таймер по-сути один, общий. Называется SysTick.
Настраивается здесь:
https://github.com/yurboc/Yurix/blob/master/Projects/EncodersToArrows/main.c#L38
А используется здесь: (этот метод вызывается каждые 3 мс)
https://github.com/yurboc/Yurix/blob/master/Projects/EncodersToArrows/stm32f0xx_it.c#L102

**Comment by Falc-0n** [comment]
Хорошо, попробую убрать RC поначалу и опустить частоту. Спасибо!

**Comment by yurboc** [comment]
См. коммит 86e2143f6f929ce1e8faf03f1996336dec63537c

**Comment by Falc-0n** [comment]
Что, с крутилками наконец всё ОК?

**Comment by AlexMarkin** [comment]
Я выпаял оттуда RC и вроде все работает без глюков.

**Comment by Falc-0n** [comment]
Пойду напьюсь.)
значит, не зря мучили.

**Comment by AlexMarkin** [comment]
Рано, вдруг еще что-нибудь вылезет)

**Comment by AlexMarkin** [comment]
Ну, сейчас погонял, один раз таки дернулось от лестниц, но некритично, поживем с этим.

**Comment by AlexMarkin** [comment]
Все таки немного набирает помехи. Может еще попробуем снизить частоту немного?

**Comment by Falc-0n** [comment]
Ок, сделаем.

**Comment by yurboc** [comment]
Я так понимаю, задача больше неактуальна? Работает более-менее стабильно? Закрываю.

Если запланируете обновлять оборудование, поставьте в ручки абсолютные энкодеры вместо относительных. Стрелки поворачивайте сервоприводом вместо шагового двигателя. Это упростит подготовку квеста перед запуском игроков.
