### ISSUE TITLE
Подключить 4 зелёные кнопки в Машине Времени

### ISSUE THREAD

**Issue by yurboc** [yurboc/Yurix#5]
Логика работы:
* Пройдены все задания в Лаборатории
* Включается дым-машина
* Свет в Лаборатории гаснет
* Двери в Машину Времени открываются
* Игроки выставляют правильную дату
* Игроки закрывают двери
* Игроки нажмают кнопки
* Начало полёта

**Comment by Falc-0n** [comment]
Юр, у микросхем драйверов реле ты все входы разводил (т.е. все входы подключил к плате STM32)?
Просто хочу понять, мы только дописываем код для зажигания подсветки кнопок, и цепляем подсветку на свободный выход драйвера реле? 
Или нужно еще прокинуть провод от свободного порта STM до одного из входов драйвера реле?

**Comment by yurboc** [comment]
Да, все выходы разведены и подключены к плате. Что куда подключено описано здесь:
https://raw.githubusercontent.com/yurboc/Yurix/master/Documentation/Hardware/TeslaMainBoard/TeslaMainBoard_layout.jpg
https://github.com/yurboc/Yurix/blob/master/Documentation/Hardware/TeslaMainBoard/TeslaMainBoard_layout.txt

Как выходы задействованы в прошивке - смотри здесь:
https://github.com/yurboc/Yurix/blob/master/FreeRTOS/Projects/TeslaMainBoard/drivers-board/hardware_defines.h

Если подсветка потребляет не более 500 мА, то можешь сразу подключать между выходами
"+12" и "вых.6". Если больше - то подключи к этим выходам реле.

**Comment by yurboc** [comment]
Если подключишь к эти выходам, то управляй командами
**STM_TESLA_RELAYOn(RELAY_6);**
и
**STM_TESLA_RELAYOn(RELAY_6);**

**Comment by yurboc** [comment]
Всё что по "подсветке" кнопок - в задачу  #7.
Эта задача - про реагирование на нажатие кнопок.

**Comment by Falc-0n** [comment]
Реакцию контроллера машины на повторное нажатие Дима вроде бы исправил.

**Comment by yurboc** [comment]
То есть можно выставить сигнал и не снимать до перезапуска квеста?
Если да, убирай секундную снятие сигнала: как только сигнал получен, задачу можно усыплять (vTaskSuspend).

**Comment by Falc-0n** [comment]
Это со слов Саши, я в железе пока не проверял.
А что, оставить как есть будет хуже?

**Comment by yurboc** [comment]
Если Дима исправил, то можно оставить как есть. Хуже не будет.
