### ISSUE TITLE
Анимация "полёта" в машине времени

### ISSUE THREAD

**Issue by yurboc** [yurboc/Yurix#6]
На газоразрядных индикаторах должны выставляться даты от 09.06.1932 до текущей даты.

Необходимо синхронизировать "анимацию даты" со звуковым сопровождением и освещением.

**Comment by yurboc** [comment]
Денис, этот код надо будет доработать - скорость изменения даты на индикаторе надо подобрать в соотвтетствии с тем, что происходит в Машине Времени во время полёта.

**Comment by Falc-0n** [comment]
То есть, вместо беспорядочного появления цифр на табло, должны считаться даты подряд по календарю? И скорость изменения коррелирует с частотой моргания света?

**Comment by yurboc** [comment]
А вот это лучше узнать у Саши.
Он вчера обещал зарегистрироваться в этом проекте. Ждём его комментариев здесь =)

**Comment by AlexMarkin** [comment]
Да, Денис полностью прав

**Comment by AlexMarkin** [comment]
Денис, сделаешь эту вещь?

**Comment by Falc-0n** [comment]
Займусь на майских, посмотри почту плз. Есть вопросы по алгоритму машины.

**Comment by yurboc** [comment]
Готово. Дата меняется синхронно со звуковым сопровождением.
