### ISSUE TITLE
Программа управления нарушает работу прошивки

### ISSUE THREAD

**Issue by yurboc** [yurboc/Yurix#8]
Не соблюдается логика прохождения квеста. 

1. Если открыть лабораторию, то ты не получаешь возможность управлять Иаковом из квеста, т.е. Иаков не включается, если поставить правильные значения. Т.е. вмешавшись здесь, ты вынужден все делать с компьютера, т.к. дальнейшие действия заблокированы

2. Если открыть машину времени командой, то внутри не работают дисплеи (горят на нулях) и запустить ее изнутри невозможно. Это опять же нужно делать командой.

**Comment by Falc-0n** [comment]
Почему так происходит?

**Comment by yurboc** [comment]
Новые обработчики добавлять здесь:
https://github.com/yurboc/Yurix/blob/master/FreeRTOS/Projects/TeslaMainBoard/tasks-common/communication.c#L139

Чтобы прошивка начала проверять условия в лаборатоии нужно сделать вот так:
https://github.com/yurboc/Yurix/blob/master/FreeRTOS/Projects/TeslaMainBoard/tasks-common/cabinet.c#L97

А чтобы машина времени начала работать нужно сделать вот так:
https://github.com/yurboc/Yurix/blob/master/FreeRTOS/Projects/TeslaMainBoard/tasks-common/hightvoltage.c#L76

Если управлять из программы, то никто эти биты не выставляет, и задачи опроса условий в лаборатории и регуляторов на машине времени никогда не запускаются.

**Comment by yurboc** [comment]
Ты можешь добавить в интерфейс кнопки "Включить лабораторию" и "Включить Машину времени". И когда оператор нажмёт эти кнопки, соответствующие биты должны установиться в 1 в группе xOpenedLocks.

**Comment by Falc-0n** [comment]
Я пока эту программу в глаза не видел, и даже не представляю как ее править)

Я правильно понимаю, она нужна для операторов если посетители просят помощи?

**Comment by yurboc** [comment]
Да, именно так. Сейчас она используется для отладки - "открыть дверь", "включить свет", "запустить проектор". Она не умеет передавать на контроллер команду "если повёрнут ключ открой дверь и включи свет в лаборатории". Это умеет делать только контроллер на плате управления.

**Comment by AlexMarkin** [comment]
Есть гипотеза, что графит не открывал кино из-за программы. Я вчера-сегодня прогнал несколько раз без программы, все сработало хорошо.

**Comment by yurboc** [comment]
Программа не вмешивается в работу прошивки без явных действий пользователя.

Поэтому если ты не нажимал "поджечь графит", то в прошивке условие "ЕСЛИ генератор заряжен И графит включен И графит отработал ТО открыть проектор" будет выполняться.

**Comment by AlexMarkin** [comment]
Я не нажимал "поджечь графит", но кино не открывалось почему то. Как только попробовал с отключенной программой - все снова заработало стабильно

**Comment by yurboc** [comment]
Ближе к концу недели я добавлю в программу небольшой кусок кода, который будет отображать всё, что происходит с железом. Тогда станет ясно, где проблема.

**Comment by Falc-0n** [comment]
Значения с фотодатчиков Горгоны тоже будут отображаться? Я еще до этого не дошел, тогда пока не трогаю.

**Comment by yurboc** [comment]
Окей, их туда же запихну.
Кстати не забудь мой pull request смёржить, давно уже висит)

**Comment by Falc-0n** [comment]
Вчера запустили обновленную программу. Вторая вкладка только для установки битов, состояние приборов не изменяется?

**Comment by yurboc** [comment]
Для установки и проверки битов. В явном виде состояние приборов не меняется, но если ты выставишь биты так, что наступит условие для изменения, то всё сработает.

**Comment by yurboc** [comment]
В программу добавлена ещё одна страница с кнопками управления.
Она дублирует страницу "Обслуживаение", но кнопки подписаны более понятно.
Все кнопки разделены на блоки, которые соответствуют этапам квеста.
