### ISSUE TITLE
Прошивка проектора

### ISSUE THREAD

**Issue by yurboc** [yurboc/Yurix#9]
После окончания видео надо сделать так, чтобы видеоролик перезагружался автоматически.

**Comment by yurboc** [comment]
Проверьте плз с новой прошивкой

**Comment by AlexMarkin** [comment]
Юра, не очень понял, что проверить?
Ты уже заезжал и поменял сдкарту?

**Comment by yurboc** [comment]
Да. Но времени было мало, я только карту памяти пеставил, даже не включая.

**Comment by AlexMarkin** [comment]
Понял, сейчас попробую.

**Comment by AlexMarkin** [comment]
Работает раскошно, не выявил неполадок.

**Comment by Falc-0n** [comment]
Юр, какие изменения внести в файлы на карте памяти?
Я загрузил убунту с флешки, не могу найти где ты писал про изменения.

**Comment by yurboc** [comment]
Все изменения надо вносить в каталоге /home/pi/pyomxplayer/

В файле pyomxplayer.py в цикле опроса UART порта стоит задержка вроде как 0.7, вот эту строку и надо убрать.

А вообще посмотри репозиторий с omxplayer на гитхабе, там в одном из pull-request'ов рассказывали, как сделать непрерывное воспроизведение, и даже выкладывали готовый (скомпилированный) omxplayer с таким функционалом: указываешь ключ -L и о зацикливании видео искусственным способом (как сейчас) можно будет забыть.

**Comment by Falc-0n** [comment]
Стоит запрет на изменение файлов, как его обойти?

**Comment by yurboc** [comment]
Проверь переключатель защиты от записи на карте памяти.
Запусти из терминала 'sudo nautilus' и попробуй ещё раз.
В свойствах файлов, которые изменяешь, ставь права на чтение/запись/ выполнение всем.
-- 
Юрий Боцев,
+7(916)374-93-99


14.04.2015, 23:34, "Denis" <notifications@github.com>:

**Comment by Falc-0n** [comment]
Убунта требовала права максимального уровня из трех, что-то вроде "super user #1000", точно не помню. У меня там был минимальный уровень, остальное серым цветом, изменить было нельзя.
Репозитории, связанные с линуксом, для меня сейчас глухое место. Т.к. я больше железячник, чем прогер, не знаком с линуксом (совсем), плюс все на английском.
Сейчас методом тыка доделаем, по твоим рекомендациям, чтобы можно было квесты гонять. И надеюсь, больше в программную часть проектора лезть не придется))
Значит, сейчас нужно:
-получить права в убунте (как это сделать?), 
-убираем две строки в коде, о которых ты писал, и 
-заливаем склеенное видео.
Так?
Из-за увеличенной длины видео, дополнительные корректировки в коде потребуются?

**Comment by yurboc** [comment]
Если решили склеивать видео, то этого достаточно. Просто залейте его, ничего не меняя в коде.

**Comment by Falc-0n** [comment]
Это же не избавит от глюков, они просто станут реже?
Хорошее решение было бы - без кнопки сброса на проекторе, чтоб не завязываться на память операторов.

**Comment by yurboc** [comment]
Да, имеено так, они станут реже. Как избавиться от глюков навсегда, с вероятностью 100%, и не копаясь в линуксе - я не знаю.

**Comment by Falc-0n** [comment]
Есть вероятность, что удаление тех двух строчек поможет? Подскажи плз, как на убунте получить права на изменение файлов?

**Comment by yurboc** [comment]
Да, есть вероятность что удаление той одной строчки (с задержкой после получения данных из uart) частично решит проблему. Но наверняка я сказать не могу.Обычно никаких прав в убунте не требуется. Открываешь файл и изменяешь его. Ну либо открываешь конслоь, пишешь sudo nautilus и работаешь из него.

**Comment by Falc-0n** [comment]
Я вчера делал так: загрузился с флешки под убунтой, без установки, вставил карту памяти, заше в раздел home/... нашел нужный файл, открыл, удалил строчку. Сохранить убунта не дала, т.к. прав не хватает.
lock на карте помяти не проверял, но думаю если бы он был залочен, убунта бы не показала доступность редактирования для суперпользователя?

**Comment by yurboc** [comment]
Загрузившись с флешки, нажми кнопку в верхнем левом углу (аналог "Пуск" в винде), набери в поиске Terminal, открой его. Это аналог консоли в винде.В терминале напиши "sudo nautilus". Откроется нечто похожее на проводник в винде. Зайди через него на флешку и открой файл. Теперь права на редактирования будут.Если ты запустишь проводник (nautilus) не из терминала через sudo (а от имени обычного пользователя), то у тебя нехватает прав на запись в тот файл со скриптом. -- Юрий Боцев,+7(916)374-93-99   15.04.2015, 11:05, "Denis" <notifications@github.com>:Я вчера делал так: загрузился с флешки под убунтой, без установки, вставил карту памяти, заше в раздел home/... нашел нужный файл, открыл, удалил строчку. Сохранить убунта не дала, т.к. прав не хватает. lock на карте помяти не проверял, но думаю если бы он был залочен, убунта бы не показала доступность редактирования для суперпользователя?—Reply to this email directly or view it on GitHub.

**Comment by Falc-0n** [comment]
Спасибо! будем пытаться.

**Comment by AlexMarkin** [comment]
Я залил новое видео и удалил строку 66 из файла. Видео воспроизводится, но я увидел 2 бага:
1. Проектор зависает
2. Включается режим непрерывного воспроизведения. 
Что можно сделать?

**Comment by yurboc** [comment]
Значит проблема не в той строке, а где-то ещё. Не знаю. Когда будет время, посмотрю что ещё можно сделать.

**Comment by AlexMarkin** [comment]
Пока залил видео с сотней роликов

**Comment by Falc-0n** [comment]
Сейчас, пока не поставили внешнюю кнопку Reset, можно проверить - правда ли проблема возникает "на рубеже" двух кусков видео, или случайно. Сейчас по идее до сотого ролика не должно глючить ни разу.

**Comment by yurboc** [comment]
Эти зависания очень сложно отлавливаются. И почему они происходят я пока не знаю. Основных версий две: переполнение буфера, пока перезапускается ролик  и данные не собираются. Вторая - основная, что проблема в плеере, который некорректно ставится на паузу прямо перед началом видео или сразу после окончания.
